// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace HOAHome.Areas.nh.Controllers {
    public partial class HomeController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d):this() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.RedirectToRouteResult RemoveHome() {
            return new T4MVC_RedirectToRouteResult(Area, Name, ActionNames.RemoveHome);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.nh.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "nh";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string Homes = "Homes";
            public readonly string AddHome = "AddHome";
            public readonly string RemoveHome = "RemoveHome";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string AddHome = "~/Areas/nh/Views/Home/AddHome.aspx";
            public readonly string Homes = "~/Areas/nh/Views/Home/Homes.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_HomeController: HOAHome.Areas.nh.Controllers.HomeController {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ViewResult Homes() {
            var callInfo = new T4MVC_ViewResult(Area, Name, ActionNames.Homes);
            return callInfo;
        }

        public override System.Web.Mvc.ViewResult AddHome() {
            var callInfo = new T4MVC_ViewResult(Area, Name, ActionNames.AddHome);
            return callInfo;
        }

        public override System.Web.Mvc.RedirectToRouteResult AddHome(string addressFull, double latitude, double longitude) {
            var callInfo = new T4MVC_RedirectToRouteResult(Area, Name, ActionNames.AddHome);
            callInfo.RouteValueDictionary.Add("addressFull", addressFull);
            callInfo.RouteValueDictionary.Add("latitude", latitude);
            callInfo.RouteValueDictionary.Add("longitude", longitude);
            return callInfo;
        }

        public override System.Web.Mvc.RedirectToRouteResult RemoveHome(System.Guid homeId) {
            var callInfo = new T4MVC_RedirectToRouteResult(Area, Name, ActionNames.RemoveHome);
            callInfo.RouteValueDictionary.Add("homeId", homeId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
