// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace HOAHome.Controllers {
    public partial class UserHomeController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UserHomeController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UserHomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult CreateChildByAddress() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.CreateChildByAddress);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Details() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Details);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Edit() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Delete() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult CreateChild() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.CreateChild);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UserHomeController Actions { get { return MVC.UserHome; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "UserHome";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string CreateChildByAddress = "CreateChildByAddress";
            public readonly string Details = "Details";
            public readonly string Create = "Create";
            public readonly string Edit = "Edit";
            public readonly string Delete = "Delete";
            public readonly string List = "List";
            public readonly string CreateChild = "CreateChild";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string CreateChildByAddress = "~/Views/UserHome/CreateChildByAddress.aspx";
            public readonly string Details = "~/Views/UserHome/Details.aspx";
            public readonly string Edit = "~/Views/UserHome/Edit.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_UserHomeController: HOAHome.Controllers.UserHomeController {
        public T4MVC_UserHomeController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult CreateChildByAddress(System.Guid parentId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreateChildByAddress);
            callInfo.RouteValueDictionary.Add("parentId", parentId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreateChildByAddress(System.Guid parentId, HOAHome.Models.UserHome userHome, string addressFull, double latitude, double longitude) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreateChildByAddress);
            callInfo.RouteValueDictionary.Add("parentId", parentId);
            callInfo.RouteValueDictionary.Add("userHome", userHome);
            callInfo.RouteValueDictionary.Add("addressFull", addressFull);
            callInfo.RouteValueDictionary.Add("latitude", latitude);
            callInfo.RouteValueDictionary.Add("longitude", longitude);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Details(System.Guid id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Details);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Create);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create(HOAHome.Models.UserHome entity) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Create);
            callInfo.RouteValueDictionary.Add("entity", entity);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(System.Guid id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Delete(System.Guid id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Delete);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult List() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.List);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(HOAHome.Models.UserHome entity) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            callInfo.RouteValueDictionary.Add("entity", entity);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreateChild(System.Guid parentId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreateChild);
            callInfo.RouteValueDictionary.Add("parentId", parentId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreateChild(System.Guid parentId, HOAHome.Models.UserHome entity) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreateChild);
            callInfo.RouteValueDictionary.Add("parentId", parentId);
            callInfo.RouteValueDictionary.Add("entity", entity);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
